

### **1. Introduction to NumPy and Importing NumPy**

#### **What is NumPy?**
NumPy, short for **Numerical Python**, is one of the most powerful and popular libraries in Python for numerical computing. It provides support for working with arrays and matrices, along with a wide collection of mathematical functions to operate on these data structures. NumPy is the backbone of many other scientific computing libraries in Python, such as pandas, scikit-learn, and TensorFlow.

#### **Why Use NumPy?**
1. **Efficient Storage and Processing**: NumPy arrays are more efficient than Python lists in terms of memory usage and computational speed.
2. **Mathematical Operations**: Provides a wide range of mathematical and statistical functions.
3. **Interoperability**: Works seamlessly with other libraries like pandas and matplotlib.
4. **Ease of Use**: Simplifies the process of working with multidimensional data.

#### **How to Install NumPy**
Before you can use NumPy, ensure it is installed in your Python environment. Use the following command to install it:

```python
pip install numpy
```

#### **Importing NumPy**
To use NumPy in your Python script, import it using the standard alias:

```python
import numpy as np
```

This alias (np) is a convention followed by most Python developers, making code easier to read and consistent across projects.

#### **First NumPy Example**
Let’s write a small example to create a NumPy array and print it:

```python
import numpy as np

# Creating a 1D array
array = np.array([1, 2, 3, 4, 5])
print("NumPy Array:", array)
```
Output:
```
NumPy Array: [1 2 3 4 5]
```

---

### **2. Array Creation**

#### **1D Arrays**
A one-dimensional (1D) array is the simplest form of a NumPy array. It is essentially a list of numbers.

**Example:**
```python
# Creating a 1D array
array_1d = np.array([10, 20, 30, 40])
print("1D Array:", array_1d)
```
Output:
```
1D Array: [10 20 30 40]
```

#### **2D Arrays**
A two-dimensional (2D) array is like a table or matrix, consisting of rows and columns.

**Example:**
```python
# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:")
print(array_2d)
```
Output:
```
2D Array:
[[1 2 3]
 [4 5 6]]
```

#### **3D Arrays**
A three-dimensional (3D) array adds another dimension, making it similar to a cube of numbers.

**Example:**
```python
# Creating a 3D array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:")
print(array_3d)
```
Output:
```
3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
```

#### **Multi-Dimensional Arrays**
NumPy allows the creation of arrays with more than three dimensions. These arrays can represent complex data structures.

**Example:**
```python
# Creating a 4D array
array_4d = np.random.rand(2, 2, 2, 2)
print("4D Array:")
print(array_4d)
```
Output (example):
```
4D Array:
[[[[0.1 0.2]
   [0.3 0.4]]

  [[0.5 0.6]
   [0.7 0.8]]]

 [[[0.9 1.0]
   [1.1 1.2]]

  [[1.3 1.4]
   [1.5 1.6]]]]
```

---

### **3. NumPy Attributes**

NumPy arrays come with several useful attributes that help describe their properties, such as their shape, size, and data type.

#### **1. Data Type (dtype)**
This attribute tells you the type of elements stored in the array.

**Example:**
```python
array = np.array([1, 2, 3])
print("Data Type:", array.dtype)
```
Output:
```
Data Type: int64
```

#### **2. Shape**
The `shape` attribute gives the dimensions of the array as a tuple. For example, a 2x3 matrix has the shape `(2, 3)`.

**Example:**
```python
array = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", array.shape)
```
Output:
```
Shape: (2, 3)
```

#### **3. Number of Dimensions (ndim)**
The `ndim` attribute tells you the number of dimensions (axes) of the array.

**Example:**
```python
array = np.array([[1, 2], [3, 4]])
print("Number of Dimensions:", array.ndim)
```
Output:
```
Number of Dimensions: 2
```

#### **4. Item Size (itemsize)**
This gives the size (in bytes) of one element in the array.

**Example:**
```python
array = np.array([1, 2, 3], dtype=np.int32)
print("Item Size:", array.itemsize)
```
Output:
```
Item Size: 4
```

#### **5. Total Bytes (nbytes)**
The `nbytes` attribute gives the total number of bytes consumed by the array.

**Example:**
```python
array = np.array([1, 2, 3, 4], dtype=np.int32)
print("Total Bytes:", array.nbytes)
```
Output:
```
Total Bytes: 16
```

---

### **4. Creating Different Types of Arrays**

NumPy provides several functions to create arrays quickly and efficiently. Below are the most common methods:

#### **1. Arrays of Zeros**
Creates an array filled with zeros.

**Example:**
```python
zeros_array = np.zeros((2, 3))
print("Array of Zeros:")
print(zeros_array)
```
Output:
```
Array of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]]
```

#### **2. Arrays of Ones**
Creates an array filled with ones.

**Example:**
```python
ones_array = np.ones((3, 2))
print("Array of Ones:")
print(ones_array)
```
Output:
```
Array of Ones:
[[1. 1.]
 [1. 1.]
 [1. 1.]]
```

#### **3. Empty Arrays**
Creates an array without initializing the values (values may be random).

**Example:**
```python
empty_array = np.empty((2, 2))
print("Empty Array:")
print(empty_array)
```
Output (example):
```
Empty Array:
[[1.2e-10 1.3e-10]
 [1.4e-10 1.5e-10]]
```

#### **4. Identity Matrix (eye)**
Creates a square 2D array with ones on the diagonal and zeros elsewhere.

**Example:**
```python
identity_matrix = np.eye(3)
print("Identity Matrix:")
print(identity_matrix)
```
Output:
```
Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

#### **5. Diagonal Arrays (diag)**
Creates an array with specified values along its diagonal.

**Example:**
```python
diagonal_array = np.diag([10, 20, 30])
print("Diagonal Array:")
print(diagonal_array)
```
Output:
```
Diagonal Array:
[[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]
```

#### **6. Arrays with arange**
Creates an array with a range of values, similar to Python’s `range()` function.

**Example:**
```python
arange_array = np.arange(1, 10, 2)
print("Array with arange:", arange_array)
```
Output:
```
Array with arange: [1 3 5 7 9]
```

#### **7. Arrays with linspace**
Creates an array with equally spaced values between a start and an end.

**Example:**
```python
linspace_array = np.linspace(0, 1, 5)
print("Array with linspace:", linspace_array)
```
Output:
```
Array with linspace: [0.   0.25 0.5  0.75 1.  ]
```

---

### **5. Accessing Elements of an Array**

#### **1. Accessing Elements in 1D Arrays**
You can access elements of a 1D array using their index positions, similar to Python lists. Indexing starts from `0`.

**Example:**
```python
array = np.array([10, 20, 30, 40, 50])
print("First element:", array[0])  # Accessing the first element
print("Last element:", array[-1])  # Accessing the last element
```
Output:
```
First element: 10
Last element: 50
```

#### **2. Accessing Elements in 2D Arrays**
In 2D arrays, you use row and column indices to access elements.

**Example:**
```python
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Element at row 1, column 2:", array_2d[1, 2])  # Element in 2nd row, 3rd column
```
Output:
```
Element at row 1, column 2: 6
```

#### **3. Accessing Elements in Multi-Dimensional Arrays**
For higher-dimensional arrays, you need to specify indices for each axis.

**Example:**
```python
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Element at (1, 1, 0):", array_3d[1, 1, 0])
```
Output:
```
Element at (1, 1, 0): 7
```

---

### **6. NumPy Slicing**

Slicing allows you to extract portions of an array by specifying start, stop, and step indices.

#### **1. Slicing 1D Arrays**
**Example:**
```python
array = np.array([10, 20, 30, 40, 50])
print("Slice from index 1 to 3:", array[1:4])
print("Every second element:", array[::2])
```
Output:
```
Slice from index 1 to 3: [20 30 40]
Every second element: [10 30 50]
```

#### **2. Slicing 2D Arrays**
You can slice rows and columns using ranges.

**Example:**
```python
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("First two rows and columns 1 to 2:")
print(array_2d[:2, 1:3])
```
Output:
```
First two rows and columns 1 to 2:
[[2 3]
 [5 6]]
```

---

### **7. Reshaping and Flattening an Array**

#### **1. Reshaping Arrays**
The `reshape()` method changes the shape of an array without altering its data.

**Example:**
```python
array = np.array([1, 2, 3, 4, 5, 6])
reshaped = array.reshape(2, 3)  # 2 rows, 3 columns
print("Reshaped Array:")
print(reshaped)
```
Output:
```
Reshaped Array:
[[1 2 3]
 [4 5 6]]
```

#### **2. Flattening Arrays**
The `flatten()` method converts a multi-dimensional array into a 1D array.

**Example:**
```python
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
flattened = array_2d.flatten()
print("Flattened Array:", flattened)
```
Output:
```
Flattened Array: [1 2 3 4 5 6]
```

---

### **8. Data Types in NumPy**

NumPy supports a variety of data types (integers, floats, booleans, etc.). You can specify the data type when creating an array or convert it later using the `astype()` method.

#### **Example:**
```python
array = np.array([1, 2, 3], dtype=np.float64)
print("Data Type:", array.dtype)

# Converting to integer
converted = array.astype(np.int32)
print("Converted Array:", converted)
print("New Data Type:", converted.dtype)
```
Output:
```
Data Type: float64
Converted Array: [1 2 3]
New Data Type: int32
```

---

### **9. Operators in NumPy**

NumPy provides a range of operators for arithmetic, relational, and logical operations.

#### **1. Arithmetic Operations**
Arithmetic operations are performed element-wise.

**Example:**
```python
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print("Addition:", array1 + array2)
print("Multiplication:", array1 * array2)
```
Output:
```
Addition: [5 7 9]
Multiplication: [4 10 18]
```

#### **2. Relational Operations**
Relational operators compare elements and return a boolean array.

**Example:**
```python
array = np.array([10, 20, 30])
print("Greater than 15:", array > 15)
```
Output:
```
Greater than 15: [False  True  True]
```

#### **3. Logical Operators**
Logical operations such as `logical_and`, `logical_or`, and `logical_not` can be applied element-wise.

**Example:**
```python
array = np.array([10, 20, 30])
print("Logical AND:", np.logical_and(array > 15, array < 30))
```
Output:
```
Logical AND: [False  True False]
```

---

### **10. Data Analysis with NumPy**

NumPy simplifies various statistical calculations, such as averages, standard deviation, and correlation coefficients.

#### **1. Average, Mean, and Median**

**Example:**
```python
array = np.array([10, 20, 30, 40, 50])
print("Mean:", np.mean(array))
print("Median:", np.median(array))
```
Output:
```
Mean: 30.0
Median: 30.0
```

#### **2. Correlation Coefficients**

**Example:**
```python
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
print("Correlation Coefficient:")
print(np.corrcoef(array1, array2))
```
Output:
```
Correlation Coefficient:
[[1. 1.]
 [1. 1.]]
```

#### **3. Standard Deviation**

**Example:**
```python
array = np.array([10, 20, 30, 40, 50])
print("Standard Deviation:", np.std(array))
```
Output:
```
Standard Deviation: 14.142135623730951
```

#### **4. Generating Random Data**
You can use `np.random.normal` to generate data for statistical analysis.

**Example:**
```python
random_data = np.random.normal(0, 1, 10)
print("Random Data:", random_data)
```
Output (example):
```
Random Data: [ 0.1 -0.5  0.3 -1.2 ...]
```

---




#### **Question 1**
**Problem Statement:**
Write a Python function that takes a NumPy array as input and performs the following tasks:
1. Print the data type (`dtype`) of the array.
2. Print the shape of the array.
3. Print the number of dimensions of the array (`ndim`).

**Input:**
A single NumPy array, e.g., `np.array([[1, 2, 3], [4, 5, 6]])`.

**Task:**
Ensure the function can handle arrays of different dimensions (1D, 2D, 3D).

---


In [7]:
import numpy as np
def analyze_array(array):
    print("Data type of the array:",array.dtype)
    print("Shape of the array:",array.shape)
    print("Dimension of the array:",array.ndim)

array_1d = np.array([1,2,3,4,5])
analyze_array(array_1d)

array_2d = np.array([[10,20,30],[50,60,70]])
analyze_array(array_2d)

array_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
analyze_array(array_3d)

Data type of the array: int32
Shape of the array: (5,)
Dimension of the array: 1
Data type of the array: int32
Shape of the array: (2, 3)
Dimension of the array: 2
Data type of the array: int32
Shape of the array: (2, 2, 3)
Dimension of the array: 3



#### **Question 2**
**Problem Statement:**
Create a NumPy array using `np.linspace()` with 100 evenly spaced numbers between 0 and 50. Perform the following operations:
1. Reshape the array into a 10x10 matrix.
2. Slice out the first 5 rows and the last 5 columns of the reshaped matrix.
3. Find the sum of all elements in the sliced matrix.

**Input:**
No direct input; the array is generated using `np.linspace()`.

**Task:**
Return the sliced matrix and its sum.

---


In [19]:
import numpy as np
def process_matrix():
    array = np.linspace(0,50,100)
    matrix = array.reshape(10,10)
    sliced_matrix = matrix[:5,-5:]
    matrix_sum = np.sum(sliced_matrix)
    return sliced_matrix,matrix_sum

print("Sliced Matrix:\n", sliced_matrix)
print("Sum of Sliced Matrix:", matrix_sum)

Sliced Matrix:
 [[ 2.52525253  3.03030303  3.53535354  4.04040404  4.54545455]
 [ 7.57575758  8.08080808  8.58585859  9.09090909  9.5959596 ]
 [12.62626263 13.13131313 13.63636364 14.14141414 14.64646465]
 [17.67676768 18.18181818 18.68686869 19.19191919 19.6969697 ]
 [22.72727273 23.23232323 23.73737374 24.24242424 24.74747475]]
Sum of Sliced Matrix: 340.90909090909093



#### **Question 3**
**Problem Statement:**
Using a 2D NumPy array of random integers between 1 and 50 (size 6x6), perform the following:
1. Identify all elements greater than 30 and replace them with the value -1.
2. Calculate the average of the modified matrix.
3. Count the number of occurrences of -1 in the modified matrix.

**Input:**
Generate the array using `np.random.randint()`.

**Task:**
Return the modified matrix, its average, and the count of -1.

---


In [27]:
import numpy as np
def process_random_matrix():
    matrix = np.random.randint(1,51,size=(6,6))
    matrix[matrix>50] = -1
    #average = np.average(matrix)
    average = np.mean(matrix)
    count_of_minus_one = np.count_nonzero(matrix == -1)
    return matrix,average,count_of_minus_one

modified_matrix, average, count_of_minus_one = process_random_matrix()
#print("Matrix: \n", matrix)
#print('Average of matrix: \n', average)
#print("Count of minus 1: \n", count_of_minus_one)

print("Modified Matrix:\n", modified_matrix)
print("Average of Modified Matrix:", average)
print("Count of -1 in Modified Matrix:", count_of_minus_one)




Modified Matrix:
 [[27 22 13  7  8 19]
 [20 30 13 28 42 17]
 [ 9 33 34  3 23 25]
 [42 34 15  7 18  1]
 [ 1 14 21 13 38  7]
 [ 4 18 11 46  5 40]]
Average of Modified Matrix: 19.666666666666668
Count of -1 in Modified Matrix: 0



#### **Question 4**
**Problem Statement:**
Create a function that accepts a NumPy array and a number `n`. The function should:
1. Flatten the input array.
2. Find all the indices of elements in the flattened array that are divisible by `n`.
3. Return a list of these indices.

**Input:**
- A NumPy array (e.g., `np.array([[10, 15, 20], [25, 30, 35]])`).
- A divisor (e.g., `5`).

**Task:**
Handle arrays of any size and ensure proper handling of divisors.

---

In [32]:
import numpy as np

def find_divisible_indices(array, n):
    # Handle edge case: Check if divisor is zero
    if n == 0:
        raise ValueError("Divisor 'n' cannot be zero.")
    
    # Step 1: Flatten the array
    flat_array = array.flatten()
    
    # Step 2: Identify divisible elements
    condition = flat_array % n == 0
    
    # Step 3: Find indices of elements satisfying the condition
    indices = np.where(condition)[0]
    
    # Step 4: Convert indices to a list and return
    return indices.tolist()

# Example Usage
array = np.array([[10, 15, 20], [25, 30, 35]])
n = 5
indices = find_divisible_indices(array, n)
print("Indices of elements divisible by {}: {}".format(n, indices))

Indices of elements divisible by 5: [0, 1, 2, 3, 4, 5]



#### **Question 5**
**Problem Statement:**
Write a Python function that takes a 2D NumPy array and a target sum as input. The function should find all pairs of elements in the array whose sum is equal to the target. For each pair, return their indices in the format `(row1, col1, row2, col2)`.

**Input:**
- A 2D NumPy array (e.g., `np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])`).
- A target sum (e.g., `10`).

**Task:**
The function should not count duplicate pairs or self-pairs (e.g., `(4, 6)` is the same as `(6, 4)`).

---
